Auto hide sidebar only if we showed it by hovering
Skullsneeze/SidebarHoverToggle pull request #1
Opened 2016-11-20 22:44 UTC by math2001

Hi!

I changed the code a bit so that it hides the side bar only when it has been opened by hovering the gutter.

So, if you show the sidebar in any other way, it will stay on event if you hover something else

Thanks again, this plugin is awesome!

Matt

2016-11-23 15:57 UTC, Skullsneeze requested changes
Thanks for the feature. Looks good! Could you add some comments that explain the logic you're using. I'll retest and merge everything afterwards.

2016-11-23 21:10 UTC, math2001 commented
Ok, I'll do that

2016-11-25 05:26 UTC, math2001 commented
Sorry @Skullsneeze , I forgot about it, but here it is. Tell me what you think about it.

2016-11-25 23:13 UTC, math2001 commented
@Skullsneeze hello? ([You're plugin's wanted](https://forum.sublimetext.com/t/an-idea-on-side-bar/24603))

2016-12-06 13:04 UTC, merged

2016-12-06 13:05 UTC, Skullsneeze commented
Hey @math2001, sorry for the late reply, work has been crazy lately. Commit looks good, and is merged!

Thanks for the enhancement!

2016-12-06 19:57 UTC, math2001 commented
Cool! Thanks!